services:
  - type: web
    name: elms
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: elms-db
          property: connectionString
    healthCheckPath: /

databases:
  - name: elms-db
    databaseName: elms
    user: elms_user
    plan: free

